import React, { useEffect, useRef } from 'react';
import { Flex } from 'antd';
import './Payment.css'
import { useReactToPrint } from "react-to-print";

function Sozlesme({ student, contact, onClose }) {
  const contentRef = useRef();
  const handlePrint = useReactToPrint({ contentRef, onAfterPrint: () => { onClose() } });

  useEffect(() => {
    handlePrint();
  }, []);

  return (

    <div className="PrintArea timesNewRoman" ref={contentRef}>
      <div className="PrintPadding" style={{ padding: "2rem", position: "relative" }}>
        <Flex vertical={true} gap="small">
          <h1 style={{ textAlign: "center" }}>GENEL HUSUSLAR</h1>
          <ol style={{ listStyle: "decimal" }}>
            <li>Öğrencinin bir sonraki eğitim öğretim yılında okulun ara sınıfına devam etmek istemesi durumunda, yukarıda “Ödeme Bilgileri Bölümünde Öğrenci İçin Belirlenen Eğitim Ücreti” üzerinden artış yapılacaktır.</li>
            <li>Bir sonraki yılda öğrencinin aynı okulun ara sınıfına devam emek istemesi durumunda öğrencinin eğitim ücreti, Özel Öğretim Kurumları Yönetmeliğinin 53’üncü maddesinde yer alan hüküm kapsamında tespit edilir. </li>
            <li>Kurumumuz, bir sonraki yılın eğitim ücretini ve diğer (takviye kursları, yemek, servis, kıyafet, kırtasiye, yatakhane vb.) ücretlerini, ocak ayından itibaren mayıs ayının sonuna kadar ilan eder. Bu ilanlarda ders yılı veya ders saati ücretiyle birlikte, peşin veya taksitli ödemeler ve diğer indirimler de belirtilir.</li>
            <li>Sosyal ve kültürel faaliyetler, gezi ve gözlem gibi diğer etkinlikler için ücretler, faaliyet öncesi belirlenir. Kurs ve faaliyetlere katılım ise velisi izni doğrultusunda gerçekleşir.</li>
            <li>Kurumumuz, öğrenci veya velilerinden beceri eğitimi / staj çalışması adı altında ayrı bir ücret talep etmeyecektir.</li>
            <li>Kurumumuz süresi içinde eğitim ve öğretim ücretini ilan etmemesi halinde, kurumumuzda bir önceki yılın sözleşmesindeki eğitim ve öğretim ücreti geçerli olacaktır.</li>
            <li>Eğitim ve öğretim ücreti kurum adına açılan ve valiliğe bildirilen banka hesap numarasına yatırılarak tahsil edilir. Öğrencilerden alınan ücretler e-Okul sistemine işlenir ve velilerin bilgisine sunulur</li>
            <li>Okulumuz, ders yılı sonunda ücret ödemesi yapmayan öğrencinin kaydını yenilemeyebilir. Kaydı yenilenmeyen öğrencinin nakli, velisi tarafından başka bir özel okula veya öğrenci yerleştirme ve nakil komisyonu aracılığıyla resmî kurumların tabi olduğu ilgili mevzuat hükümleri çerçevesinde uygun olan resmî okula alınır.</li>
            <li>MEB Özel Öğretim Kurumları Yönetmeliğinin 56 ncı maddesi hükümlerince; sınavla öğrenci alan resmî okulların 9 uncu sınıflarına kayıt yaptırdığını belgelendirenler hariç, eğitim ve öğretim yılı başlamadan kurumumuzdan ayrılanlara, öğrencinin ödeyeceği yıllık ücretin %10 dışındaki kısmı, eğitim ve öğretim yılı başladıktan sonra kurumumuzdan ayrılanlara ise öğrencinin ödeyeceği yıllık ücretin %10’u ile öğrenim gördüğü günlere göre hesaplanan miktarın dışındaki kısmı öğrenci velisine ücret iadeleri ayrılış tarihinden itibaren en geç bir ay içerisinde yapılır.</li>
            <li>Kurumumuz tarafından öğrencinin ücretsiz okumasının uygun bulunması ve/veya öğrencinin indirim hakkı elde etmesi halinde kurumumuza ödenen ücret, eğitim ve öğretimin başladıktan en geç bir ay içerisinde öğrenci velisine geri ödenir. </li>
            <li>Herhangi bir şekilde kurumumuzdan ayrılan burslu öğrencilerden öğrenim gördüğü süre için herhangi bir ücret talep edilmeyecektir.</li>
            <li>Eğitim ve Öğretim Desteğinden faydalanan öğrenci ücretinin ödenmesi;</li>
            <ol style={{ listStyle: "lower-latin" }}>
              <li>Öğrencinin velisi bu sözleşmede belirlenen eğitim ve öğretim ücretinin Bakanlıkça karşılanacak eğitim ve öğretim desteğinin dışında kalan bedelini okula ödemekle yükümlüdür. </li>
              <li>Öğrencinin eğitim ve öğretim desteğinin çeşitli sebeplerden dolayı iptal edilmesi durumunda, kalan tutar öğrencinin velisinden tahsil edilir.</li>
            </ol>
            <li>MEB Özel Öğretim Kurumları Yönetmeliğinin Ek 2 nci maddesine göre; kurumumuzun ilan ettiği yıllık ücretin %51’i ve fazlası oranında burslu okutulan öğrencinin eğitim ve öğretim desteği Bakanlığa bildirilerek iptali istenir. </li>
            <li>Öğrencinin okula devam etmesi esastır. Devamsızlık yapan öğrencinin velisi, öğrencinin mazeretini okula bildirir. Velisi tarafından söz konusu bildirimin okula yapılmaması halinde, okul idaresi gelmeyen öğrencilerin velisiyle iletişim kurarak devamsız öğrenci hakkında veliye bilgi verir.</li>
            <li>İş bu sözleşmede yer alan hususların yerine getirilmesi ve gerekli tebligatların yapılabilmesi için velisi tarafından yukarıda belirtilen adresin yasal ikametgâh adresi olduğu ve adres değişikliği durumunda 15 gün içerisinde yazılı olarak okula bildirilmediği takdirde bu adrese yapılacak tebligat geçerli olacaktır. Öğrenci kayıt sözleşmesinin tüm hükümleri velisi tarafından eksiksiz olarak okunmuş, anlaşılmış ve herhangi bir tereddüt olmaksızın tamamen hür irade ve arzu ile kesin olarak kabul edilmiştir.</li>
          </ol>
          <h1 style={{ textAlign: "center", marginTop: "2rem" }}>ÖZEL HUSUSLAR</h1>
          <ol style={{ listStyle: "decimal" }}>
            <li>Lise kademelerinde sınıf belirleme işlemleri LGS yüzdelik dilimi, düzey belirleme sınav sonuçları ve öğrencilerin yıl içerisinde katılmış olduğu deneme sınavlarının sonuçları dikkate alınarak puan üstünlüğüne göre okul yönetimi tarafından belirlenir. İlkokul 1.sınıf olacak öğrencilerin sınıf ve öğretmen belirlemeleri eğitim öğretim yılı başlangıcında velilerin huzurunda kura çekimiyle yapılır. Öğrenci velisi hiçbir şekilde sınıf belirlemesine itiraz edemez, sınıf değişikliği talebinde bulunamaz. Öğrencilerin sınıf değişikliği, rehberlik biriminin belirlediği kriterlere göre okul yönetimi onayıyla yapılacak olup öğrenci ve velisi hiçbir şekilde sınıf değişikliğine itiraz edemez, sınıf değişikliği talebinde bulunamaz ve bunu kayıt silme gerekçesi olarak kullanamaz.</li>
            <li>Okul tarafından anlaşmalı firmalar aracılığı ile sağlanan servis hizmetlerinden sadece servis kaydı yapılan öğrenciler yararlanabilir. Her öğrenci servis araçlarını dersi olan gün ve saatlerde kullanır. Birebir etütler, kulüpler, takım çalışmaları ve dersi olmayan diğer günlerde servis hizmeti yoktur. Servis hizmetinden yararlanmak isteyen öğrenciler ancak okul tarafından önerilen anlaşmalı servis firmasını kullanabilir. Servis firması ile öğrenci velisi/vasisinin ayrıca sözleşme yapması gerekmektedir. Servis firması ile yapılan sözleşmelerde ABC Okullarının herhangi bir hukuki sorumluluğu yoktur.</li>
            <li>Öğrencinin sağlık sorunları nedeniyle kullanması gereken ölçüm cihazı, ilaç vb.’nin kullanımı ve takibine ait tüm sorumluluklar öğrenci ve velisine aittir. Okul sağlık biriminin teşhis ve tedavi etme yükümlülüğü olmayıp, anlık gelişen durumlarda ilkyardımda bulunur.</li>
            <li>Bu kayıt sözleşmesini imzalayarak kayıt işlemlerini tamamlayan veli ve öğrenci fotoğraf ve videolarının,  okulun web sayfasında, sosyal medya hesaplarında, tanıtım kataloğu, broşür, okul dergileri vb. alanlarda yapacağı her türlü tanıtım amaçlı ilan ve reklam alanlarında kullanılmasına izin vermiş sayılır.</li>
            <li>Kurum idaresinin yazılı izni olmadan öğrencilerin kendi aralarında yapacakları gezi ve etkinliklerden Kurum’un herhangi bir sorumluluğu bulunmamakta olup, Kurum yasal görevini yerine getirmek üzere sorumlular hakkında inceleme ve soruşturma başlatma hakkına da sahiptir.</li>
            <li>Öğrenci, ders saatleri içerisinde haklı ve geçerli mazeretlerin vuku halinde ancak velinin yazılı talep ve isteği ile Kurum’dan ayrılabilir.</li>
            <li>Kurum, ilçe, il veya ülke genelinde eğitim ve öğretimi aksatacak nitelikte olağandışı bir durum meydana gelmesi, sel, deprem, elverişsiz hava şartları ve benzeri durumlar, doğal afetler ile hastalık/salgın hastalık gibi nedenlerle okulda eğitim ve öğretime ara verilmesi gerekmesi halinde uzaktan eğitim yapılabilir, telafi eğitimleri düzenlenebilir. Öğrenci, kurum tarafından belirlenen takvim ve programlara uygun olarak uzaktan eğitim ve telafi eğitimlerine katılmak zorundadır. Uzaktan eğitimin içeriğini müfredata uygun şekilde düzenlemeye, uzaktan eğitimin yapılma usulünü, yapılacağı platformu belirlemeye okul yetkilidir. Yukarıda belirtilen zorunlu hallerde yapılacak olan uzaktan eğitim/telafi eğitimi okulun eğitim öğretim yapma yükümlülüğünü yerine getirmesini sağlar. Uzaktan eğitim yapılan günler için veli ücret iadesi talebinde bulunamaz.</li>
            <li>Veli kendisinin ve velisi/vasisi olduğu öğrencinin, 6698 sayılı Kişisel Verilerin Korunması Kanunu başta olmak üzere, yürürlükteki kişisel veri koruma mevzuatı ile bu hususta MEB tarafından yayımlanmış genelge ve talimatlara, Kurum politika ve kurallarına uygun davranacağını kabul ve taahhüt eder. Bu çerçevede, diğer öğrencilerin ve velilerin, Kurum yetkilileri, yöneticiler ve çalışanlarının kişisel verilerini mevzuata aykırı olarak işlemek, yayımlamak, paylaşmak yasaktır.</li>
            <li>Kurum içerisinde ders içi veya ders dışında, serviste, eğitimin online yapılması halinde online derste, mevzuata, genelge ve talimatlara, Kurum içi politika ve kurallarına, aykırı şekilde veya izin almadan bilişim araçları kullanılarak görüntü ve ses kaydı alınması, saklanması, paylaşılması yasaktır. İş bu maddeye aykırı davranış halinde, MEB mevzuatına uygun olarak disiplin hükümleri uygulanır; eylemlerin suç teşkil edecek nitelikte olması halinde ilgili makamlara bildirilir.</li>
            <li>Eğitim öğretim süreçlerinde okulumuz eğitim planlamalarına uyum kurumumuz açısından son derece önemlidir. Çağın gereklilikleri, dinamik eğitim-öğretim süreçleri, MEB’in yeni uygulamaları, okulumuz rehberlik birimi ve bilim kurulunun AR-GE çalışmaları gereğince eğitim-öğretim programlarında (ders programı ve haftalık ders saati sayısı ile ders ekleme ve çıkarma, eğitimi destekleyici faaliyetler, öğretmen değişikliği, öğrenci sınıf değişikliği, eğitim programı değişikliği vb.), MEB eğitim mevzuatına uygun değişiklik yapma hakkı ABC okullarına aittir. Okula kaydı yapılan öğrenci ve velisi okul tarafından yapılacak değişikliklere uygun hareket etmeyi kabul ve taahhüt eder. </li>
            <li>Değişik nedenlerle servis hizmeti verilmemesi halinde servis firması ile veli arasında doğabilecek uyuşmazlıklardan Kurum’un herhangi bir sorumluluğu bulunmamaktadır. Bu konuda servis firması ve veli arasında yapılan sözleşme esas olup anlaşmazlıklar bu sözleşme hükümlerine göre çözülmesi gerekmektedir. Bu nedenle söz konusu sözleşme formunun ve ödeme makbuzunun veli tarafından muhafaza edilmesi gerekmektedir. Veli, servis kullanan öğrencinin devamlı veya geçici olarak güzergah değiştirmesi halinde bu durumu Kurum’a bildirmekle yükümlüdür. </li>
            <li>Veli, Kurum ile iletişim sağlamak ve öğrencinin durumunu takip etmek üzere Kurum sistemini kullanacaktır.</li>
            <li>Veli, öğrencinin okul bünyesinde bulunan ve gizlilik içeren tüm belge ve bilgileri dışarıya çıkartmayacağını veya bu bilgileri öğrenmesi halinde üçüncü kişilerle paylaşmayacağını, dışarı bilgi çıkarılması halinde bunları ivedilikle Kurum’a iade edeceğini ve öğrencinin sosyal medya üzerinden Kurum’a yönelik paylaşımlarından sorumlu olacağını kabul eder. </li>
            <h2 style={{ marginTop: "1rem" }}>KAYIT İLE İLGİLİ ESASLAR</h2>
            <li>Okula, öğrenci kaydı öğrenci velisinin müracaatıyla yapılır. Yapılan görüşmeler sonrasında okul ile veli arasında sözleşme yapılır.</li>
            <li>Öğrenci kayıt sözleşmesinin veli tarafından imzalanması kayıt işleminin tamamlanması için yeterli değildir. Sözleşmenin imzalanması ile birlikte peşin ödeme seçilmiş kayıtlarda kayıt bedelinin, taksitli ödeme seçeneği seçilen kayıtlarda peşinatın ödenmesi ve anlaşmalı banka ile veli tahsilat sistemi işlemlerinin tamamlanması ile öğrenci kaydı tamamlanır. </li>
            <li>Yıl içinde öğrencilerimize uygulanan deneme-tarama sınav sonuçları, öğretmen görüşleri, sınıf içi ve okul içi durumları dikkate alınarak öğrencinin Anadolu Lisesinden Fen Lisesine ya da Fen Lisesinden Anadolu Lisesine geçişlerine okul yönetimi karar verebilir.</li>
            <li>Anadolu ve Fen Lisesi eğitim öğretim ücretlerine; ABC Senin Kütüphanen Programı ücreti, YKS Genel Tekrar Kamp Programı ücreti, Görsel Sanatlar dersi malzeme ücreti, Bilişim ve Bilgisayar Bilimi dersi malzeme ücreti, Uluslararası yarışmalara katılım, ulaşım, konaklama ücreti dâhil değildir.</li>
            <li>Anaokulu, ilkokul ve ortaokul kademelerinde okul tarafından belirlenen eğitim öğretim materyalleri ( basılı ve dijital eğitim platformları) kayıt ücretine dâhil değildir. Okul tarafından her yıl sene başında ilan edilen bu materyallerin eksiksiz olarak almayı veli/vasi kabul etmiş sayılır.</li>
            <h2 style={{ marginTop: "1rem" }}>DİSİPLİN İLE İLGİLİ ESASLAR</h2>
            <li>Öğrencinin, davranış ve disiplinsizlikleri hakkında MEB Okul Öncesi ve İlköğretim Kurumları Yönetmeliği’nin ile MEB Ortaöğretim Kurumları Yönetmeliği’nin öğrenci davranışları ile ilgili hükümleri aynen uygulanacaktır.</li>
            <li>Okulumuz MEB’e bağlı bir kurum olması nedeni ile ilgili mevzuata uygun okulun belirlediği kıyafet ile okula devam edilir. Okul kıyafeti, Okul tarafından belirlenen anlaşmalı kurumlardan ücret karşılığı temin edilir. Okul ile anlaşması olmayan kurumlardan temin edilen kıyafetler kullanılamaz.</li>
            <li>Öğrencinin, derslere zamanında girmesi, dersin işlenişini bozmaması, öğretmen ve arkadaşlarını derste rahatsız etmemesi gerekmektedir. </li>
            <li>Öğrenci, ders içinde ya da dışında hiçbir siyasi veya ideolojik konuşma yapamayacağı gibi, okula delici/kesici alet, radyo teyp, mp3 çalar, gazete, cep telefonu, tablet, PSP, gameboy gibi görüntü ve kayıt özelliği olan teknolojik araçlar, gayri ahlaki ve siyasi içerikli yayın, kaset, CD, vb. sigara, her türlü alkollü içecek getiremeyeceği gibi Kurum tarafından belirlenen kılık-kıyafet kurallarına ve yönetmelik hükümlerine aynen uymak zorundadır.</li>
            <li>Öğrenci, öğretmenleri tarafından istenen her türlü araç-gereç ve ders kaynaklarını zamanında getirmek, verilen ödev ve projeleri zamanında istenilen şekilde yapmak, derslerine düzenli olarak çalışmak, öğretmenleri tarafından verilen görevleri yerine getirmek zorundadır. </li>
            <li>Öğrencinin, Kurum’un demirbaşlarına veya diğer araç ve gereçlere zarar vermesi halinde veli bu zararı karşılamakla yükümlüdür. </li>
            <h2 style={{ marginTop: "1rem" }}>İNDİRİM İLE İLGİLİ ESASLAR</h2>
            <li>Ücret indirimi okul yönetim kurulunun yetkilendirdiği kişiler tarafından belirlenen şartlar ve oranlar doğrultusunda yapılır. İndirim şartlarını taşımayanlara indirim uygulanmaz.
              <br /><br />
              Burslu öğrencilerin genel başarısı yılsonunda rehberlik servisi ile yönetim kurulu tarafından değerlendirilerek kazanılan burs oranının düşürülmesi ya da devam etmesine karar verilir.
              <br /><br />
              Okuduğu öğretim yılında Disiplin Kurulu tarafından disiplin cezası alan ve davranış puanı indirilen öğrencinin burs hakkı öğretim yılı sonunda sona erer.
              <br /><br />
              Kayıt yaptırma koşulu ile uygulanan indirimler, verilen ödül, hediye ve yayınların okul yönetimince belirlenen ücretleri, kaydın silinmesi durumunda geri alınır.
              <br /><br />
              <b>
                KARDEŞ İNDİRİMİ AYNI YIL KURUMLARIMIZDA EĞİTİM GÖREN KARDEŞ ÖĞRENCİLERE UYGULANMAKTA OLUP, KARDEŞLERDEN BİRİNİN AYRILMASI, MEZUN OLMASI DURUMUNDA UYGULANAN KARDEŞ İNDİRİMİ İPTAL EDİLİR. 2024-2025 EĞİTİM ÖĞRETİM DÖNEMİNDEN İTİBAREN YENİ KAYIT OLAN %50 VE ÜZERİNDE BURS KAZANAN ÖĞRENCİLERMİZİN EĞİTİM BEDELİ HESAPLAMALARINDA KARDEŞ İNDİRİMİ ORANI %5 OLARAK UYGULANIR.
                <br /><br />
                BURSLAR, HER YIL KURUM TARAFINDAN İLAN EDİLEN ERKEN KAYIT SÜRECİ İÇİN GEÇERLİ OLAN ORANLARDIR. ERKEN KAYIT DÖNEMİNDE KAYIT YAPTIRMAYAN YADA BELİRLENEN ÖDEME VADELERİNDE ÖDEMELERİNİ YAPMAYAN  ÖĞRENCİLER BURS HAKLARINI KAYBEDER. ERKEN KAYIT SÜRECİNDE BURSLU ÖĞRENCİLER İLE İLK KEZ BURS KAZANAN ÖĞRENCİLERE AYRICA ERKEN KAYIT İNDİRİMLERİ UYGULANMAYACAKTIR.
                <br /><br />
                EĞİTİM BEDELİ HESAPLAMALARINDA KAYIT DÖNEMİ İÇİN VERİLEN ERKEN KAYIT, KARDEŞ, ÖĞRETMEN ( MİLLİ EĞİTİM BAKANLIĞINA BAĞLI KURUMLARDA ÇALIŞAN ÖĞRETMEN İLE YÜKSEKÖĞRETİM KURUMUNA BAĞLI ÜNİVERSİTELERDE ÖĞRETİM ÜYESİ OLARAK ÇALIŞANLAR VE BUNU BELGELENDİRENLER), PEŞİN ÖDEME, PERSONEL İNDİRİMİ VB. İNDİRİM ORANLARI KAYIT YILI İÇİN GEÇERLİ ORANLAR OLUP, OKUL TAKİP EDEN EĞİTİM DÖNEMLERİNDE YENİ İNDİRİM KALEMLERİ AÇABİLECEĞİ GİBİ MEVCUT İNDİRİM KALEMLERİNİN ORANLARINDA DEĞİŞİKLİK YAPMA YA DA TAMAMEN KALDIRMA HAKKINA SAHİPTİR. UYGULANAN İNDİRİMLER SONRAKİ DÖNEMLER İÇİN MÜKTESAP HAK SAYILMAZ.
                <br /><br />
                EĞİTİM VE EĞİTİM DIŞINDAKİ HİZMETLERE UYGULANMIŞ OLAN PERSONEL İNDİRİMİ, SADECE O KAYIT YILI SÜRESİNCE VE PERSONELİN İŞ İLİŞKİSİ DEVAM ETTİĞİ SÜRECE GEÇERLİDİR. PERSONELİN İŞ AKDİ EĞİTİM DÖNEMİ DEVAM EDERKEN SONA ERERSE; İŞTEN AYRILIŞ TARİHİNDEN SONRA TAHAKKUK EDECEK EĞİTİM VE EĞİTİM DIŞINDAKİ HİZMETLERİN ÜCRETLERİNDE PERSONEL İNDİRİMİ UYGULANMAYACAKTIR VE İNDİRİMSİZ OLARAK FATURA EDİLEREK ÖDENECEKTİR.
                <br /><br />
                AYRICA OKULUMUZUN DÜZENLEMİŞ OLDUĞU SINAVLAR İLE İLK KEZ BURS KAZANAN YA DA BURS ORANI YÜKSELEN ÖĞRENCİLERİN, VARSA DAHA ÖNCE UYGULANAN ERKEN KAYIT İNDİRİMİ VE DEVAM EDEN ÖĞRENCİ İNDİRİMLERİ İPTAL EDİLİR. EĞİTİM BEDELİ, AÇIKLANAN YENİ YIL EĞİTİM ÜCRETLERİ ÜZERİNDEN KAZANILAN BURS ORANI VE DİĞER İNDİRİMLERİ HESAPLANARAK BULUNUR.
                <br /><br />
                KAZANILAN BURSLAR İLGİLİ ÖĞRETİM DÖNEMİ SONUNA KADAR GEÇERLİDİR.
                <br /><br />
                ÖRGÜN EĞİTİM KURUMLARININ TÜRÜ İTİBARIYLA (ANAOKULU 3 YAŞ, 1. SINIF, 5. SINIF VE 9. SINIFLARA) KADEME BAŞLANGIÇ KAYITLARINDA EKSTRA YAPILAN İNDİRİM ORANLARI TEK SEFERLİKTİR, SONRAKİ YILLARIN EĞİTİM ÜCRETİ HESABINDA DİKKATE ALINMAZ, DİĞER YILLARDA UYGULANMAZ VE MÜKTESAP HAK SAYILMAZ.
                <br /><br />
                ÖĞRENCİNİN EĞİTİM BEDELİ HESAPLAMASINDA BİRDEN FAZLA İNDİRİMİ BULUNMASI DURUMUNDA, HER İNDİRİM YÜZDE ORANI KADEMELİ OLARAK, BİR ÖNCEKİ İNDİRİM TUTARI DÜŞÜLDÜKTEN SONRA KALAN EĞİTİM BEDELİNE SONRAKİ İNDİRİM ORANI UYGULANARAK HESAPLANIR.
                <br /><br />
                EĞİTİM BEDELİNE UYGULANAN BURS, KARDEŞ, ÖĞRETMEN, PERSONEL, ERKEN KAYIT, KENDİ ÖĞRENCİMİZ, PEŞİN ÖDEME VB. BİRDEN FAZLA İNDİRİM ORANI BULUNMASI DURUMUNDA, EĞİTİM BEDELİNE PEŞİN ÖDEME İNDİRİMİ DAHİL EN FAZLA 4 (DÖRT) İNDİRİM KALEMİ UYGULANIR. YEMEK BEDELİNE SADECE PEŞİN ÖDEME İNDİRİMİ UYGULANIR.
                <br /><br />
                PEŞİN ÖDEME İNDİRİMİ UYGULANAN KAYITLARDA ÜCRETLERİN BELİRLENEN ÖDEME VADESİNDE ÖDENMEMESİ DURUMUNDA, UYGULANAN PEŞİN ÖDEME VE ERKEN KAYIT İNDİRİMLERİ İPTAL EDİLİR, ÖDEMENİN YAPILDIĞI AY İÇİN BELİRLENEN EĞİTİM VE YEMEK BEDELLERİ İLE İNDİRİM ORANLARI UYGULANIR.
              </b>
              <br /><br />
              Öğrenim gördüğü yıla ilişkin indirim şartları ortadan kalkan öğrencilerin bir sonraki yılın eğitim ücretleri Özel Öğretim Kurumları Yönetmeliği 53. Maddesi uyarınca, öğrencinin okula kayıt olduğu yıldaki indirimsiz ücrete öğrenim gördüğü her yıl için Yönetmelik 53/1. maddede belirtilen oranda artış yapılarak belirlenir.
            </li>
            <h2 style={{ marginTop: "1rem" }}>MALİ YÜKÜMLÜLÜKLER İLE İLGİLİ ESASLAR</h2>
            <li>Öğretim dönemi içinde zorunlu bir sebeple kayıt sildirmek isteyen öğrenci için, velisinin yazılı müracaatı gereklidir. Müracaat sonrası okul yetkilisi veya okul müdürü tarafından kayıt silme gerekçesi incelenerek öğrenci kaydı silinir. </li>
            <li>Okulumuza kayıtlı öğrencilerin ilgili programlara devam etmesi temel esastır. Devamsızlık yapılması durumunda okul tarafından, öğrenci velisine öğrenci durum belgeleri, SMS veya telefonla haber verilir. Devamsızlık nedenini rapor vb. resmi evraklar ile belgelendiremeyen öğrencilerin belirlenen süreleri aşması durumunda öğrenci kaydı okul disiplin kurulunun kararı ile silinir.</li>
            <li>Okula kayıtlı öğrencilerin devamsızlık yapması; velinin ödeme yükümlülüğünü etkilemez. Veli; öğrencinin kaydı silinmediği sürece, devam etsin veya etmesin kayıtlı olduğu programın ücretini ödemekle yükümlüdür.</li>
            <li>Öğrencinin sınıfta kalması halinde ve öğrenimine devam etmek istemesi halinde, devam edeceği sınıfa ilişkin güncel eğitim öğretim ücretini veli ödemekle yükümlüdür. </li>
            <li>Eğitim ücretlerine yemek, servis, kıyafet, yabancı dil ve ek kaynak kitapları ile kırtasiye, takviye kurs, sosyal ve kültürel faaliyetler, gezi ve gözlem gibi etkinliklere ait ücretler dahil değildir. Okulumuzda yemek hafta içi 5 (beş) gün tüm öğrencilere verilmekte olup öğrencinin sağlık sorunu olması ve bunu belgelendirmesi koşuluyla iptal edilebilir. </li>
            <li>KDV oranlarının değişmesi veya yeni vergilerin yürürlüğe konulması halinde, vergi farkı öğrenci ücretlerine aynen yansıtılır ve veliden tahsil edilir. Bununla birlikte mevcut piyasa koşulları nedeniyle yemek maliyetinde önemli oranda artış olması halinde bu durum veliye yazılı olarak bildirilecektir ve velinin bu artışı kabul etmemesi halinde Kurum, veliye yemek ücreti bakiyesini iade ederek yemek hizmeti vermeyi tek taraflı olarak sonlandırabilecektir. Bu durumda veli yemek ücreti bakiyesi haricinde herhangi bir talepte bulunmayacaktır. 3065 Sayılı Katma Değer Vergisi Kanunu 10/a maddesi ile mal teslimi veya hizmet ifası hallerinin vergiyi doğuran olay olduğu hüküm altına alınmıştır. Bu sebeple eğitim öğretim dönemini kapsayan faturalar “Eylül/Haziran” döneminde 10 eşit tutarda kesilecektir.</li>
            <li>Ödeme planı, taksit sayısı, tarih ve ödeme tutarlarında bireysel değişiklik yapılmayacaktır. Nakit ödemelerde TL dışında, başka bir para birimi ile ödeme kabul edilmeyecektir.</li>
            <li>Okul ücretinin peşin veya aylık taksitler halinde ödenmesi esastır. Peşin ödemede, Nakit/Kredi kartı ile ödeme indirim oranları dikkate alınarak kayıt sırasında ödemenin tamamı nakit ya da tüm kredi kartlarından tek çekim ile yapılabilir. Peşin ödemenin çek ile yapılabilmesi ise okul kararına bağlıdır. Kabul edilen çeklerin velinin kendi adına düzenlenmiş olması veya velinin çeki cirolaması gereklidir. Taksitli ödemenin tercih edilmesi durumunda öncelikle anlaşmalı bankanın okul tahsilat sistemi ile ödemelerin tahsili yapılacaktır. Banka ile yapılan çalışmanın olumsuz sonuçlanması durumunda kayıt bedelinin tamamı kredi kartı ile taksitli çekim yapılarak ödenebilecektir. Bu ödeme yöntemleri dışında taksitlerin nakit ödenmesi ya da okul banka hesabına havale yapılması seçenekleri kabul edilmeyecektir.</li>
            <li>Taksitli ödemelerde ödeme planı okul tarafından belirlenir. Kayıt işlemlerinde okul yönetimi tarafından belirlenen kayıt yenileme süreleri, erken kayıt ve peşin ödeme tarihleri, indirim oranları, taksit sayıları ve ödeme vadeleri uygulanır. Okul yönetimi tarafından onaylanmış geçmiş yıllara ait ödeme planları, kayıt yenileme işlemlerinde yeniden talep edilemez, müktesap hak sayılamaz. Taksitli ödemelerde taksitler okulun anlaşmış olduğu banka aracılığı ile tahsil edilir. Bankanın velinin kayıt bedeli tutarı kadar Kredili Mevduat Hesabı (KMH) tanımlaması esas olmakla birlikte, veli için onay alınamaması durumunda okulun onayı ile daha düşük tutarda ek hesap tanımlanabilir. Okulun anlaşmış olduğu bankada veli adına açılacak kredili mevduat hesabı (KMH) aracılığı ile aylık taksit tutarı ödeme tarihinde otomatik olarak okul hesabına geçer. </li>
            <li>Öğrencinin okul kaydı devem ettiği sürece anlaşmalı banka nezdinde açılacak KMH hesabının açık kalması ve ödemelerin bu hesap aracılığı ile yapılması esastır. Okul istediği banka ile anlaşabilir. Kayıt olan veli bu anlaşmaya uyacağını peşinen kabul ve taahhüt eder. Velinin ödeyeceği aylık taksit miktarı taksitin ait olduğu ayın eğitim ücreti değildir. </li>
            <li>Veli adına Kredili Mevduat Hesabı açılamaması durumunda öğrenci ödemeleri kredi kartı Mail Order yöntemi ile tahsil edilir. Mail Order ödeme seçeneği ile yapılan ödemelerde taksitler veli tarafından imzalanan Mail Order ödeme talimatı ile çekim yapılır. Belirlenen tarihte gerçekleşmeyen ödemeler için takip eden günlerde taksit tutarına ulaşılana kadar kısmi tahsilatlar yapılarak ödemenin tahsili yapılır.</li>
            <li>Ödeme Bilgileri kısmında yer alan ücretlerin banka ödeme araçları (POS, KMH vb.) ile ödenmesi halinde veli ile Banka/Bankalar arasında doğacak uyuşmazlıkların ya da ödeme sorunlarının Kurum’a herhangi bir yükümlülük getirmeyeceği hususunda da taraflar arasında mutabakata varılmıştır. Vadesinde bankaya yapılmayan ödemeden dolayı oluşan gecikme faizi borcu banka tarafından veliye tahakkuk ettirilecektir. Bu borç veli ile banka arasındandır. </li>
            <li>Sözleşme kapsamında sunulan hizmetlere ilişkin ödemeler anne, baba veya vasi tarafından Kurum hesabına yapılacak olup vade tarihlerinde ödeme yapılmaması halinde anne, baba veya vasi temerrüde düşecektir. Kurum’un personeli olan veli veya vasinin ödemediği bedel aylık ücretinden kesilecektir. Bu halde mevzuatta öngörülen en yüksek faiz oranının yüzde yüz fazlası uygulanacaktır</li>
            <li>Veli, mutabık kalınan Ödeme Bilgileri gereğince doğan borcun tamamını veya taksitlerden birini belirtilen tarihte ödemediği takdirde Kurum yönetiminin hukuki süreçlere başvurmasına sebebiyet verirse tüm yargılama masraflarını, icra inkâr tazminatını, vekâlet ücretini, faizi, yasal her türlü mükellefiyeti derhal ödemeyi peşinen kabul ve taahhüt eder.</li>
            <li>Okul taksitlerinden gecikmiş borcu bulunan velilerimizin borçlarının tamamını ödemeleri gerekmektedir. Aksi takdirde bir sonraki eğitim-öğretim yılı için Özel Öğretim Kurumları yönetmeliği 55/2 maddesi ve Özel Eğitim Kurumları Öğrenci ve Kursiyer Ücretleri Tespit ve Tahsil Yönetmenliği’ nin 8. maddesi 3. bendi gereğince kayıt yenileme takviminde kayıt yenilemeyen, peşin, peşinat veya taksitleri ödenmeyen öğrencilerimizin yeni dönem kayıt yenileme işlemi yapılmayacak ve sınıf tahsis edilmeyecektir. Ancak, bununla birlikte, kaydın herhangi bir şekilde yenilenmesi veya yenilenmiş sayılması (kaydı Velisi tarafından yenilenmediği halde öğrencinin okula gelmeye veya Velisi tarafından gönderilmeye devam etmesi) halinde Veli, izleyen öğretim yılı için, Özel Öğretim Kurumları Yönetmeliğinin 53. maddesinde belirtilen artışın uygulanması suretiyle bulunacak miktarı, eğitim-öğretim ücreti olarak ödemeyi kabul ve taahhüt eder.</li>
            <li>Zamanında yapılmayan ödemeler için mevzuatta öngörülen en yüksek faiz oranının yüzde yüz fazlası gecikme zammı olarak uygulanır, veli telefon, SMS ve gecikme ihbarnamesi ile uyarılır, okulun sunduğu öğretim hizmetleri durdurulur ve veli hakkında yasal takibat yapılır. </li>
            <li>Veli, işbu Sözleşme kapsamında meydana gelebilecek her türlü uyuşmazlıkta, Kurum defter ve kayıtlarının delil niteliğinde olacağını ve bankadaki kayıtlara herhangi bir şekilde itiraz edilmeyeceği kabul eder</li>
            <li>Kurum, işbu Sözleşme hükümlerine uymayan öğrencinin veya velinin kaydının Kurum’dan alınmasını tek taraflı olarak talep etme hakkına sahip olup, veli böyle bir durumda itiraz etmeksizin kaydı aldıracağını kabul eder. Ayrıca öğrencinin bilişsel, sosyal, duygusal veya fiziksel bir sorun yaşaması halinde ve bu durumun Kurum’u veya diğer öğrencileri ya da çalışanları etkilenesi halinde ilgili komisyon ve Kurum psikolojik danışmanlarının değerlendirilmesi ile Veli’den öğrencinin kaydının alınması talep edilebilir. </li>
            <li>Okul yönetiminin belirlediği çalışma takvimi valilik tarafından onaylanır. Onaylanan çalışma takvimine göre Okulumuzda eğitim öğretim başlar. Valilik tarafından onaylanan çalışma takvimine göre resmi tatiller, alınan tatil kararları ile yarıyıl ve yaz tatili uygulanır. Valilik, MEB kararıyla uygulanan tatil süreleri ya da öğrencinin herhangi bir sebeple yıl içerisinde yapmış olduğu devamsızlık (sağlık sorunu, seyahat vb.) nedeniyle belirlenen yemek, eğitim- öğretim ve sair ücretlerden herhangi bir indirim yapılmayacaktır.</li>
            <li>Kurum tarafından velinin e-posta ve telefon numarası bilgisi sözleşme süreçlerinin yürütülmesi ve bilgilendirme yapılması amacıyla kullanılacak olup Veli bunların doğru olduğunu taahhüt eder ve bu amaçla kullanılmasına izin verir. Kuruma ait web sitesi üzerinden yapılacak online kayıtlarda sözleşme ve diğer ekler Veli’nin e-posta hesabına ve/veya cep telefonuna link olarak gönderilir. Veli sms ile gelen bağlantıya veya e-posta olarak gelen bağlantıyı seçerek kendisine iletilen sözleşme ve varsa diğer ekleri görüntüler , bu süreçte güvenlik sağlanması amacıyla  sms ve e-mail adresi doğrulama tek kullanımlık şifre vb. güvenlik uygulamaları kullanılır. Veli bu süreci tamamlamakla birlikte sözleşme’yi imzalamış sayılır. </li>
          </ol>
          <h2 style={{ marginTop: "1rem" }}>TAAHHÜT</h2>
          <p style={{ marginTop: "1rem" }}>ABC Okulları’na (Göksu Program Yazılım Eğitim Öğretim Bilg.Sis.Yay.İnş.Taah.ve San.Ltd.Şti) 2024-2025 Eğitim-öğretim yılında verilecek öğretim programı hizmeti karşılığında, {student?.new?.education + student?.new?.food} Türk Lirası borcumuzdur. Ekteki ödeme miktar ve tarihlerini gösteren ödeme planı, işbu sözleşmenin ayrılmaz parçası mahiyetindedir.</p>
          <p style={{ marginTop: "1rem" }}>İşbu sözleşmenin müzakeresinde, imzalanmasında, tatbikinde ve ihtilaf vukuunda  (0312) 260 47 77 numaralı telefondan hukuk departmanımız ile irtibata geçebilir; soru ve şikayetlerinizi yöneltebilirsiniz.</p>
          <p style={{ marginTop: "1rem" }}>Üst üste iki taksiti vadesinde ödemediğimiz takdirde ayrıca ihtara mahal kalmaksızın bakiye borcumuzun muacceliyet kesbedeceğini ve bu tarihten itibaren geciken taksitlerin kanuni gecikme bedellerinin tarafımıza ait olacağını, ihtilaf vukuunda bu sözleşmeden doğabilecek tüm anlaşmazlıklarda Ankara Batı Mahkemeleri ve İcra dairelerinin yetkili olduğunu kabul ederim.</p>
          <p style={{ marginTop: "1rem" }}>İş bu kayıt sözleşmenin tüm hükümleri tarafımızca eksiksiz olarak okunmuş ve herhangi bir tereddüt olmaksızın anlaşılmış olup, tamamen hür irade ve arzumla yukarıdaki ikaz çerçevesinde sözleşme şartlarını kesin olarak kabul ediyorum, iş bu sözleşmenin bir nüshası tarafıma teslim edilmiştir.</p>
          <Flex justify="space-between" style={{ marginTop: "1rem" }}>
            <p>T.C. Kimlik No: {contact?.nationalID}</p>
            <p>{contact?.fullName}</p>
          </Flex>

        </Flex>
      </div>
    </div>
  )
}

export default Sozlesme
